const items = [
  {
    category: "UX",
    comments: 0,
    createdAt: "Mon Oct 17 2022 16:38:36 GMT+0200 (Central European Summer Time)",
    description: "trebalo bi sliku ucitati",
    id: "rkXOemCCVI88NDZXyRC4",
    title: "Ne ucitava sliku",

    upVotes: 0,
  },
  {
    category: "Feature",
    comments: 3,
    createdAt: "Sat Oct 01 2022 00:04:36 GMT+0200 (Central European Summer Time)",
    description: "Stay updated on comments and solutions other people post.",
    id: "wTW4kIaIswfnb6nqXl0f",
    status: "suggestion",
    title: "Ability to follow others",
    upVotes: 42,
    userId: " sUHobX6IbPgu6pKu0BbE",
  },
  {
    category: "Feature",
    comments: 3,
    createdAt: "Sun Oct 17 2021 07:05:07 GMT+0200 (Central European Summer Time)",
    description: "Challenge-specific Q&A would make for easy reference.",
    id: "p0AwDLGjA1mLma5N2wDW",
    status: "suggestion",
    title: "Q&A within the challenge hubs",
    upVotes: 65,
    userId: " sUHobX6IbPgu6pKu0BbE",
  },
  {
    category: "Feature",
    comments: 4,
    createdAt: "Sun Oct 17 2021 15:03:22 GMT+0200 (Central European Summer Time)",
    description: "It would help people with light sensitivities and who prefer dark mode.",
    id: "Hbt1BBoewGUngeCT0ZdT",
    status: "suggestion",
    title: "Add a dark theme option",
    upVotes: 99,
    userId: " sUHobX6IbPgu6pKu0BbE",
  },
  {
    category: "Enhancement",
    comments: 2,
    createdAt: "Tue Sep 21 2021 17:02:53 GMT+0200 (Central European Summer Time)",
    description: "Easier to search for solutions based on a specific stack.",
    id: "hbUvQSxctPdRrYpkKRK8",
    status: "suggestion",
    title: "Add tags for solutions",
    upVotes: 112,
    userId: " sUHobX6IbPgu6pKu0BbE",
  },
];
